/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppModelsIndexRouteImport } from './routes/_app/models/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload.image'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiChatAgentSlugRouteImport } from './routes/api/chat.$agentSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppAgentsAgentIdRouteRouteImport } from './routes/_app/agents/$agentId/route'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents/$agentId/index'
import { Route as AppAgentsAgentIdChatRouteImport } from './routes/_app/agents/$agentId/chat'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAgentSlugRoute = ApiChatAgentSlugRouteImport.update({
  id: '/api/chat/$agentSlug',
  path: '/api/chat/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsAgentIdRouteRoute = AppAgentsAgentIdRouteRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsAgentIdRouteRoute,
} as any)
const AppAgentsAgentIdChatRoute = AppAgentsAgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppAgentsAgentIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/users': typeof AppUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$agentSlug': typeof ApiChatAgentSlugRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/agents': typeof AppAgentsIndexRoute
  '/models': typeof AppModelsIndexRoute
  '/agents/$agentId/chat': typeof AppAgentsAgentIdChatRoute
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/users': typeof AppUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$agentSlug': typeof ApiChatAgentSlugRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/agents': typeof AppAgentsIndexRoute
  '/models': typeof AppModelsIndexRoute
  '/agents/$agentId/chat': typeof AppAgentsAgentIdChatRoute
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$agentSlug': typeof ApiChatAgentSlugRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/models/': typeof AppModelsIndexRoute
  '/_app/agents/$agentId/chat': typeof AppAgentsAgentIdChatRoute
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/agents/$agentId'
    | '/api/auth/$'
    | '/api/chat/$agentSlug'
    | '/api/trpc/$'
    | '/api/upload/image'
    | '/agents'
    | '/models'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/api/auth/$'
    | '/api/chat/$agentSlug'
    | '/api/trpc/$'
    | '/api/upload/image'
    | '/agents'
    | '/models'
    | '/agents/$agentId/chat'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/api/auth/$'
    | '/api/chat/$agentSlug'
    | '/api/trpc/$'
    | '/api/upload/image'
    | '/_app/agents/'
    | '/_app/models/'
    | '/_app/agents/$agentId/chat'
    | '/_app/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatAgentSlugRoute: typeof ApiChatAgentSlugRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/': {
      id: '/_app/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$agentSlug': {
      id: '/api/chat/$agentSlug'
      path: '/api/chat/$agentSlug'
      fullPath: '/api/chat/$agentSlug'
      preLoaderRoute: typeof ApiChatAgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRouteRoute
    }
    '/_app/agents/$agentId/chat': {
      id: '/_app/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AppAgentsAgentIdChatRouteImport
      parentRoute: typeof AppAgentsAgentIdRouteRoute
    }
  }
}

interface AppAgentsAgentIdRouteRouteChildren {
  AppAgentsAgentIdChatRoute: typeof AppAgentsAgentIdChatRoute
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
}

const AppAgentsAgentIdRouteRouteChildren: AppAgentsAgentIdRouteRouteChildren = {
  AppAgentsAgentIdChatRoute: AppAgentsAgentIdChatRoute,
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
}

const AppAgentsAgentIdRouteRouteWithChildren =
  AppAgentsAgentIdRouteRoute._addFileChildren(
    AppAgentsAgentIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsAgentIdRouteRoute: typeof AppAgentsAgentIdRouteRouteWithChildren
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentsAgentIdRouteRoute: AppAgentsAgentIdRouteRouteWithChildren,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatAgentSlugRoute: ApiChatAgentSlugRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
